import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatInputModule } from '@angular/material/input';

@NgModule({
  imports: [
    //         MatAutocompleteModule,
    //       MatButtonModule,
    //         MatButtonToggleModule,
    //         MatCardModule,
    MatCheckboxModule,
    //         MatChipsModule,
    //         MatDatepickerModule,
    //         MatDialogModule,
    //         MatExpansionModule,
    //         MatGridListModule,
    //         MatIconModule,
    MatInputModule,
    //         MatListModule,
    //         MatMenuModule,
    //         MatNativeDateModule,
    //         MatPaginatorModule,
    //         MatProgressBarModule,
    //         MatProgressSpinnerModule,
    //         MatRadioModule,
    //         MatRippleModule,
    //         MatSelectModule,
    //         MatSidenavModule,
    //         MatSliderModule,
    //         MatSlideToggleModule,
    //         MatSnackBarModule,
    //         MatSortModule,
    //         MatTableModule,
    //         MatTabsModule,
    MatToolbarModule,
    //         MatTooltipModule,
    //         MatStepperModule,
  ],
  exports: [
    //         MatAutocompleteModule,
    //         MatButtonModule,
    //         MatButtonToggleModule,
    //         MatCardModule,
    MatCheckboxModule,
    //         MatChipsModule,
    //         MatDatepickerModule,
    //         MatDialogModule,
    //         MatExpansionModule,
    //         MatGridListModule,
    //         MatIconModule,
    MatInputModule,
    //         MatListModule,
    //         MatMenuModule,
    //         MatNativeDateModule,
    //         MatPaginatorModule,
    //         MatProgressBarModule,
    //         MatProgressSpinnerModule,
    //         MatRadioModule,
    //         MatRippleModule,
    //         MatSelectModule,
    //         MatSidenavModule,
    //         MatSliderModule,
    //         MatSlideToggleModule,
    //         MatSnackBarModule,
    //         MatSortModule,
    //         MatTableModule,
    //         MatTabsModule,
    MatToolbarModule,
    //         MatTooltipModule,
    //         MatStepperModule,
  ]
})

export class MaterialModule { }
